<?php

    $SENDGRID_API_KEY = 'SG.1H0XT1gRTMqzZ-5hwthqjQ.370gQCCDCjrKqjnAjDaT4qrxAwnLjAC0T1MaX6aGk10';
    $STRIPE_SECRET_TEST_API_KEY = 'sk_test_zFMuyMBC60raTKDdLGzR4wdb';
    $STRIPE_PUBLISHABLE_API_KEY = 'pk_test_CVpEzpXzTZ97XvjAR1suM1m6';
    $STRIPE_SECRET_API_KEY = '';
    $STRIPE_PUBLISHABLE_API_KEY = '';

?>