<?php

    $SENDGRID_API_KEY = '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';
    $STRIPE_SECRET_TEST_API_KEY = 'sk_test_zFMuyMBC60raTKDdLGzR4wdb';
    $STRIPE_PUBLISHABLE_API_KEY = 'pk_test_CVpEzpXzTZ97XvjAR1suM1m6';
    $STRIPE_SECRET_API_KEY = '';
    $STRIPE_PUBLISHABLE_API_KEY = '';

?>